name: CI/CD Pipeline 1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: build-and-deploy
    env:
      IMAGE_REGISTRY: docker.io
      IMAGE_REPOSITORY: elishevafefer
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          addons: ingress
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: elishevafefer
          password: 0548485764

      - name: Build and Push Bitcoin Service Image
        run: |
          docker build -t $IMAGE_REGISTRY/$IMAGE_REPOSITORY/bitcoinservice:latest ./BitcoinService
          docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/bitcoinservice:latest

      - name: Build and Push Worker Service Image
        run: |
          docker build -t $IMAGE_REGISTRY/$IMAGE_REPOSITORY/someworkerservice:latest ./SomeWorkerService
          docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/someworkerservice:latest

      - name: Apply Kubernetes files
        run: |
          kubectl apply -f K8S/ # Apply your Kubernetes deployment files

      # now you can run kubectl to see the pods in the cluster
      - name: kubectl
        run: |
          kubectl get pods
          kubectl get services

